### ISSUE TITLE
Insecure coding pattern: Missing default case in switch statements 

### ISSUE THREAD

**Issue by paser4se** [mthmulders/futbolin#109]
Greetings, 

We are security researchers and we are looking for insecure coding patterns and configurations in the microservice architecture repositories. In your repository, we have found that your code does not have a default case in the switch statement. According to the Common Weakness Enumeration organization, this is a security weakness. See the link https://cwe.mitre.org/data/definitions/478.html

Source: https://github.com/mthmulders/futbolin/blob/master/webapp/src/test/java/it/mulders/futbolin/webapp/security/MockClaims.java

Fix: Fix #108 

I am interested to know if you agree with the findings. Any feedback is appreciated.

**Comment by mthmulders** [comment]
Thanks for reaching out. I definitely do agree that not having a default case in a switch statement is an insecure coding pattern.

In this case, I think I'm going to address it. The code you have found resides in a folder with test code, and the class itself is a mock for another class. As such, it is not deployed into a production environment and therefore I consider the risk mitigated.

I'd love to hear if this makes sense to you.

**Comment by paser4se** [comment]
Makes sense. Thanks for the feedback.

**Comment by mthmulders** [comment]
You're welcome. Good luck with your research!
